### ISSUE TITLE
Some code fixes

### ISSUE THREAD

**Issue by pfetsch** [tirthajyoti/UCI-ML-API#3]
To run the code, I had to make some fixes:
- ``UCI_ML_Functions.py`` line 29: ``df = df.iloc[1:nrows:2][[0,1,2,3,4,5,6]]`` When I download the table the columns are indexed 0 to 6.
- Line 209: ``url="https://archive.ics.uci.edu/ml/datasets.php?format=&task=&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=list",`` (``datasets.php`` instead of ``.html``).
- Line 520: ``local_directory = cwd + "/" + str(directory)`` (``/`` instead of ``\\``).

The following is not necessary, but nice:
- ``Choice.py`` line 117: ``print(f"OK, downloading all datasets of {task} task. This will take some time...")`` In this context it should not be filtered according to size but the task.

Thank you for sharing your code!

**Comment by tirthajyoti** [comment]
Thanks!
